### PR TITLE
Refactoring and new features

### PR DESCRIPTION
**Pull request by rafaelcn**
Hello @luizperes.

Code has been refactored, documentation was added and for everything else you can just see the commit messages. :smile:

### CODE REVIEW

**Comment by luizperes** [comment]
Travis broke because of other known problems. _// I will have to take change the file, as we changed the source tree_

It looks great! Thanks!

**Comment by rafaelcn** [comment]
No problems. Coming soon new features! :-)

**Comment by ryukinix** [comment]
I can add now the `CONTRIBUTING.md` about the version system numerating?

**Comment by luizperes** [comment]
Please @ryukinix

**Comment by ryukinix** [comment]
Right, I will create in soon.

**Pull request merged**
