### PR TITLE
FloatExpr operator support

### LINKED ISSUE #5: Implementation of the symbol `$`
Initially I was thinking about using the char `$` for converting the current cell back and forth with `float` and `int`, that would have some implications with the `LLVM IRBuilder`, since we would need to implement suppport to `floating numbers` for each arithmetic operation, debug and so on... Although, my real concerns are related on how we would do it... I was thinking of using `union` for that

### PR DESCRIPTION
**Pull request by rafaelcn**
The support of the `$` operator, known in Brain as the FloatExpr is now supported and it closes #5!  :tada: 

Tests are as well included :-)

### CODE REVIEW

**Comment by rafaelcn** [comment]
Something is weird with the tests, check that out @luizperes :astonished:

**Comment by luizperes** [comment]
What do you mean @rafaelcn ?

**Comment by luizperes** [comment]
It seems to be working here (https://travis-ci.org/luizperes/brain/builds/150682743). Thanks for closing the issue #5 :)

**Comment by rafaelcn** [comment]
No problem, glad it is working! :-)

**Pull request merged**
